import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import Link from "next/link";
import "./globals.css";
import { ThemeProvider } from "./theme-provider";

const poppins = Poppins({
  variable: "--font-poppins-sans",
  subsets: ["latin"],
  weight: ["500", "600", "700"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={`${poppins.variable} antialiased`}>
        <ThemeProvider
          attribute="class"
          defaultTheme="dark"
          enableSystem
          disableTransitionOnChange
        >
          <main className="min-h-screen max-w-6xl mx-auto my-8">
            {children}
          </main>
          <footer className="w-full bg-card">
            <div className="max-w-6xl h-10 mx-auto flex justify-between items-center">
              <Link href={"https://isahil.vercel.app/"}>Sahil Dev</Link>
              <p>
                <Link href={"https://isahil.vercel.app/"}>sahil.dev</Link>{" "}
                &copy; 2024
              </p>
            </div>
          </footer>
        </ThemeProvider>
      </body>
    </html>
  );
}
